baseurl = "https://outsiderdata.netlify.com/"
languageCode = "en-us"
title = "Outsider Data Science"

theme = "anatole"
author = "Arthur Steinmetz"
copyright = "&copy; 2017-2022. All rights reserved."
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
# logo="/img/favicon.png"
enableEmoji = true
enableRobotsTXT = true

[indexes]
  tag = "tags"
  topic = "topics"

[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[params]
  # Shown in the home page
  description = "Putting what's in here, out there. With R."
  subtitle = "Putting what's in there, out there. With R."
  images = ["img/logo_lg.jpg"]
  profilePicture = "img/logo_lg.png"
  builtWith = true
  mainSections = ["post"]
  # favIcon = "favicons/"
  displayMode = "dark"
  
  #googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  # highlightjs = "androidstudio"
  #dateFormat = "02 Jan 2006"
  singleDateFormat = "Mon, Jan 2, 2006"
  indexDateFormat = "Mon, Jan 2, 2006"
  listDateFormat = "Jan 2"
  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
  
  [[params.SocialIcons]]
  icon = "fab fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/adababbage"

  [[params.SocialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/apsteinmetz"

  [[params.SocialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/asteinmetz/"

  [[params.SocialIcons]]
  icon = "fab fa-stack-overflow"
  title = "Twitter"
  url = "https://twitter.com/adababbage"

[menus]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 100
    identifier = "Home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight =4
    identifier="contact"
    url = "/contact/"
  [[menu.main]]
    name = "Blogroll"
    pre = "<i class='fa fa-blog fa-fw'></i>"
    weight =4
    identifier="blogroll"
    url = "/blogroll/"

