project:
  type: website

website:
  title: "Outsider Data Science"
  site-url: "https://outsiderdata.netlify.app/"
  twitter-card: true
  google-analytics: "G-BVDKXJLKEL"
  navbar:
    left:
      - text: Blog
        file: index.qmd
      - text: About
        file: about.qmd
      - icon: house-fill
        url: "https://artsteinmetz.com"
      - icon: linkedin
        href: "https://www.linkedin.com/in/asteinmetz/"
      - text: "{{< fa brands bluesky >}}"
        href: "https://bsky.app/profile/apsteinmetz.bsky.social"
      - icon: mastodon
        href: "https://fosstodon.org/@adababbage"
      - icon: github
        href: "https://github.com/apsteinmetz"
      - icon: rss
        href: index.xml
      - text: "{{< fa blog >}}"
        file: blogroll.qmd
      - text: App Demos
        file: demos.qmd


format:
  html:
    theme:
      dark: darkly
      light: cerulean
    # css: styles.css
    toc: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

editor: source
freeze: auto

